config/routes.rb
Rails.application.routes.draw do
  namespace :chalie_vice do
    resources :letters
  end
  namespace :chalie_vice do
    resources :items
  end
  root 'tool#index'

  resources :items
  resources :makers

  post '/order', to: 'tool#order'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/maker.rb
class Maker < ApplicationRecord
  has_many :items

  scope :sorted_by, -> (sort_key) { order(sort_key) }
  scope :search_query, -> (query) { where('name LIKE (?)', "%#{query}%").or(where('person LIKE (?)', "%#{query}%"))}

  filterrific(
    default_filter_params: { sorted_by: 'id' },
    available_filters: [
        :sorted_by,
        :search_query,
      ]
  )

  enum ship_from_location: {
    maker: 1,
    arts: 2,
  }
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
  before_action :set_maker, only: [:show, :edit, :update, :destroy]

  # GET /makers
  # GET /makers.json
  def index
    @filterrific = initialize_filterrific(
      Maker,
      params[:filterrific]
    ) or return
    @makers = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /makers/1
  # GET /makers/1.json
  def show
  end

  # GET /makers/new
  def new
    @maker = Maker.new
  end

  # GET /makers/1/edit
  def edit
  end

  # POST /makers
  # POST /makers.json
  def create
    @maker = Maker.new(maker_params)

    respond_to do |format|
      if @maker.save
        format.html { redirect_to @maker, notice: 'Maker was successfully created.' }
        format.json { render :show, status: :created, location: @maker }
      else
        format.html { render :new }
        format.json { render json: @maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makers/1
  # PATCH/PUT /makers/1.json
  def update
    respond_to do |format|
      if @maker.update(maker_params)
        format.html { redirect_to @maker, notice: 'Maker was successfully updated.' }
        format.json { render :show, status: :ok, location: @maker }
      else
        format.html { render :edit }
        format.json { render json: @maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makers/1
  # DELETE /makers/1.json
  def destroy
    @maker.destroy
    respond_to do |format|
      format.html { redirect_to makers_url, notice: 'Maker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maker
      @maker = Maker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maker_params
      params.require(:maker).permit(:name, :person, :email, :tel, :tel_person, :condition, :payment_site, :closing_date, :bank_name, :branch_name, :bank_account_type, :bank_account_number, :ship_from_location, :remarks)
    end
end

app/views/makers/_form.html.slim
= form_for(maker) do |f|
  - if maker.errors.any?
    #error_explanation
      h2
        = pluralize(maker.errors.count, "error")
        |  prohibited this maker from being saved:
      ul
        - maker.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label 'メーカー名'
    = f.text_field :name
  .field
    = f.label '担当者'
    = f.text_field :person
  .field
    = f.label '担当者メールアドレス'
    = f.text_field :email
  .field
    = f.label '電話番号(会社)'
    = f.text_field :tel
  .field
    = f.label '電話番号(携帯)'
    = f.text_field :tel_person
  .field
    = f.label '条件'
    = f.text_field :condition
  .field
    = f.label '支払サイト'
    = f.text_field :payment_site
  .field
    = f.label '締め日'
    = f.text_field :closing_date
  .field
    = f.label '銀行名'
    = f.text_field :bank_name
  .field
    = f.label '支店名'
    = f.text_field :branch_name
  .field
    = f.label '口座種別'
    = f.text_field :bank_account_type
  .field
    = f.label '口座番号'
    = f.text_field :bank_account_number
  .field
    = f.label '発送元'
    = f.select :ship_from_location, Item.ship_from_locations.map{|key, value| [key, value]}
  .field
    = f.label '備考'
    = f.text_area :remarks
  .actions
    = f.submit

app/views/makers/_list.html.slim
#filterrific_results
  table.table.table-striped.table-bordered.table-hover.dataTable.no-footer.dtr-inline
    thead
      tr
        th 仕入先名
        th 担当者
        th メールアドレス
        /th Tel
        /th Tel person
        /th Condition
        /th Payment site
        /th Closing date
        /th Bank name
        /th Branch name
        /th Bank account type
        /th Bank account number
        /th Remarks
        th[colspan="3"]
    tbody
      - @makers.each do |maker|
        tr
          td = maker.name
          td = maker.person
          td = maker.email
          /td = maker.tel
          /td = maker.tel_person
          /td = maker.condition
          /td = maker.payment_site
          /td = maker.closing_date
          /td = maker.bank_name
          /td = maker.branch_name
          /td = maker.bank_account_type
          /td = maker.bank_account_number
          /td = maker.remarks
          td = link_to 'Show', maker
          td = link_to 'Edit', edit_maker_path(maker)
          td = link_to 'Destroy', maker, method: :delete, data: { confirm: 'Are you sure?' }
= paginate @makers

app/views/makers/edit.html.slim
h1 style="margin-top: 0;" Editing Maker

= render 'form', maker: @maker
= link_to 'Show', @maker
|  | 
= link_to 'Back', makers_path

app/views/makers/index.html.slim
.row
  h1.page-header Listing Makers

.pull-right
  = form_for_filterrific @filterrific do |f|
    = f.text_field(:search_query, class: 'filterrific-periodically-observed', placeholder: '検索')
    = render_filterrific_spinner

== render partial: 'makers/list'

br
= link_to 'New Maker', new_maker_path

app/views/makers/index.js.slim
= js = escape_javascript(render partial: 'makers/list', locals: { makers: @makers })
$("#filterrific_results").html("<%= js %>");

app/views/makers/new.html.slim
h1 style="margin-top: 0;" New Maker

= render 'form', maker: @maker
= link_to 'Back', makers_path

app/views/makers/show.html.slim
p#notice
  = notice
p
  strong メーカー名:
  = @maker.name
p
  strong 担当者:
  = @maker.person
p
  strong 担当者メールアドレス:
  = @maker.email
p
  strong 電話番号(会社):
  = @maker.tel
p
  strong 電話番号(携帯):
  = @maker.tel_person
p
  strong 条件:
  = @maker.condition
p
  strong 支払サイト:
  = @maker.payment_site
p
  strong 締め日:
  = @maker.closing_date
p
  strong 銀行名:
  = @maker.bank_name
p
  strong 支店名:
  = @maker.branch_name
p
  strong 口座種別:
  = @maker.bank_account_type
p
  strong 口座番号:
  = @maker.bank_account_number
p
  strong 備考:
  = @maker.remarks
= link_to 'Edit', edit_maker_path(@maker)
|  | 
= link_to 'Back', makers_path